### ISSUE TITLE
Pressing the Comma button causes a Force Close

### ISSUE THREAD

**Issue by robisaks** [krishnalalstha/Spannable#1]
LogCat:

06-25 14:38:34.776: E/AndroidRuntime(10425): FATAL EXCEPTION: main
06-25 14:38:34.776: E/AndroidRuntime(10425): java.lang.IndexOutOfBoundsException: setSpan (17 ... 18) ends beyond length 14
06-25 14:38:34.776: E/AndroidRuntime(10425):    at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:945)
06-25 14:38:34.776: E/AndroidRuntime(10425):    at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:527)
06-25 14:38:34.776: E/AndroidRuntime(10425):    at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:520)
06-25 14:38:34.776: E/AndroidRuntime(10425):    at android.widget.SpellChecker$SpellParser.init(SpellChecker.java:403)
06-25 14:38:34.776: E/AndroidRuntime(10425):    at android.widget.SpellChecker.spellCheck(SpellChecker.java:224)
06-25 14:38:34.776: E/AndroidRuntime(10425):    at android.widget.TextView.updateSpellCheckSpans(TextView.java:7810)
06-25 14:38:34.776: E/AndroidRuntime(10425):    at android.widget.TextView.sendOnTextChanged(TextView.java:7638)
06-25 14:38:34.776: E/AndroidRuntime(10425):    at android.widget.TextView.handleTextChanged(TextView.java:7681)
06-25 14:38:34.776: E/AndroidRuntime(10425):    at android.widget.TextView$ChangeWatcher.onTextChanged(TextView.java:8044)
06-25 14:38:34.776: E/AndroidRuntime(10425):    at android.text.SpannableStringBuilder.sendTextChange(SpannableStringBuilder.java:892)
06-25 14:38:34.776: E/AndroidRuntime(10425):    at android.text.SpannableStringBuilder.change(SpannableStringBuilder.java:352)
06-25 14:38:34.776: E/AndroidRuntime(10425):    at android.text.SpannableStringBuilder.change(SpannableStringBuilder.java:266)
06-25 14:38:34.776: E/AndroidRuntime(10425):    at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:443)
06-25 14:38:34.776: E/AndroidRuntime(10425):    at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:420)
06-25 14:38:34.776: E/AndroidRuntime(10425):    at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:29)
06-25 14:38:34.776: E/AndroidRuntime(10425):    at android.view.inputmethod.BaseInputConnection.replaceText(BaseInputConnection.java:663)
06-25 14:38:34.776: E/AndroidRuntime(10425):    at android.view.inputmethod.BaseInputConnection.commitText(BaseInputConnection.java:188)
06-25 14:38:34.776: E/AndroidRuntime(10425):    at com.android.internal.widget.EditableInputConnection.commitText(EditableInputConnection.java:149)
06-25 14:38:34.776: E/AndroidRuntime(10425):    at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:279)
06-25 14:38:34.776: E/AndroidRuntime(10425):    at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:77)
06-25 14:38:34.776: E/AndroidRuntime(10425):    at android.os.Handler.dispatchMessage(Handler.java:99)
06-25 14:38:34.776: E/AndroidRuntime(10425):    at android.os.Looper.loop(Looper.java:137)
06-25 14:38:34.776: E/AndroidRuntime(10425):    at android.app.ActivityThread.main(ActivityThread.java:4575)
06-25 14:38:34.776: E/AndroidRuntime(10425):    at java.lang.reflect.Method.invokeNative(Native Method)
06-25 14:38:34.776: E/AndroidRuntime(10425):    at java.lang.reflect.Method.invoke(Method.java:511)
06-25 14:38:34.776: E/AndroidRuntime(10425):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
06-25 14:38:34.776: E/AndroidRuntime(10425):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556)
06-25 14:38:34.776: E/AndroidRuntime(10425):    at dalvik.system.NativeStart.main(Native Method)

**Comment by krishnalalstha** [comment]
Thanks rob for helping me to find the errors.and of course  I will be very much grateful to you if u explain the issue with step of reproduction.

**Comment by robisaks** [comment]
Steps to reproduce:

1) Down src from gitub
2) Compile and push apk to phone
3) Type a word, followed by a comma
4) App crashes.

**Comment by krishnalalstha** [comment]
there was a issue of crash when two comma typed consequently which i have already updated. its fine with word and then comma with my side.

**Comment by robisaks** [comment]
I'm using a galaxy nexus with android 4.0.4

**Comment by krishnalalstha** [comment]
may be a version problem .I have implemented the same things in my app. you can check here https://play.google.com/store/apps/details?id=com.braindigit.sms.scheduler.

**Comment by robisaks** [comment]
I get the same crash in your live application. Reported it via the normal reporting engine, you should see it in the Google play developer area.

**Comment by krishnalalstha** [comment]
thanks Rob, it was problem of ice cream sandwich . i have fixed and updated. check it out again

**Comment by robisaks** [comment]
I applied your changes,  this resolves the crash, but now the EditText deletes the text preceding the comma, and the comma itself.

For example, if I enter "test,", once I hit the comma, it will delete everything in the EditText. tapping items in the popup list works as expected.

**Comment by robisaks** [comment]
Nevermind, I think the issue was being caused by some modifications I had made to the original code.

**Comment by krishnalalstha** [comment]
yaps, cause of validation. if the typed word is valid (is in contact list) and is number it doesnt removes. but if user type invalid word in reference to contact then removes when comma is typed.
