### ISSUE TITLE
some question about edit in this control

### ISSUE THREAD

**Issue by kylin17** [krishnalalstha/Spannable#2]
Hi, krishnalalstha. Thanks for your code and This is a good solution for developing SMS applications.
The problem is when I add some contacts and hide the soft keyboard, then touch the control, I can't see the focus.
Sometimes when I add contact or delete a contact, the text in the control will be replace with "" or disorder.
Another question is how to add more than one contact  in this control by one time?

**Comment by krishnalalstha** [comment]
To Add more than one contact with in this EditText. first of all you collect the contact which you want to add at  time in the in array list (lets say selectedList)then iterate over to add to EditText. Something like 

for (String name : selectedList) {
                //this method add span text to EditText which you can find in CustomMultiAutocomplete.java.
                objEditText.addTextView(name);
                                 //add "," between the control
                phoneNum.append(",");
                                //move the cursor position to the
                phoneNum.setSelection(phoneNum.getText().toString().length());
            }

hope it helps you.

**Comment by laaptu** [comment]
I hope kylin17,your issue is resolved
